// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsvP7A4HwecS2Hf5CEIRvNjm7frnWA_sM',
    appId: '1:315403975897:web:0f898236e3c4063ff2d2c8',
    messagingSenderId: '315403975897',
    projectId: 'findit-44da9',
    authDomain: 'findit-44da9.firebaseapp.com',
    storageBucket: 'findit-44da9.firebasestorage.app',
    measurementId: 'G-XCKM767J18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxPEQEr4iradwvAXiTfrBJC8JaEf0Rvjo',
    appId: '1:315403975897:android:12842cd2f98f79f2f2d2c8',
    messagingSenderId: '315403975897',
    projectId: 'findit-44da9',
    storageBucket: 'findit-44da9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEL_9etqh5hGiGbrAWwJcTltlIqBFWbTE',
    appId: '1:315403975897:ios:a92d9b97f53d8432f2d2c8',
    messagingSenderId: '315403975897',
    projectId: 'findit-44da9',
    storageBucket: 'findit-44da9.firebasestorage.app',
    iosClientId: '315403975897-75qdb1d1edp1cv6jjp365fteesm52jkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.finditApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsvP7A4HwecS2Hf5CEIRvNjm7frnWA_sM',
    appId: '1:315403975897:web:6ab6019c5ebe6ee9f2d2c8',
    messagingSenderId: '315403975897',
    projectId: 'findit-44da9',
    authDomain: 'findit-44da9.firebaseapp.com',
    storageBucket: 'findit-44da9.firebasestorage.app',
    measurementId: 'G-YVNK23Y4N1',
  );
}
